In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('traffic.csv')

In [3]:
df.head()

,event,date,country,city,artist,album,track,isrc,linkid
0,click,2021-08-21,Saudi Arabia,Jeddah,Tesher,Jalebi Baby,Jalebi Baby,QZNWQ2070741,2d896d31-97b6-4869-967b-1c5fb9cd4bb8
1,click,2021-08-21,Saudi Arabia,Jeddah,Tesher,Jalebi Baby,Jalebi Baby,QZNWQ2070741,2d896d31-97b6-4869-967b-1c5fb9cd4bb8
2,click,2021-08-21,India,Ludhiana,Reyanna Maria,So Pretty,So Pretty,USUM72100871,23199824-9cf5-4b98-942a-34965c3b0cc2
3,click,2021-08-21,France,Unknown,"Simone & Simaria, Sebastian Yatra",No Llores Más,No Llores Más,BRUM72003904,35573248-4e49-47c7-af80-08a960fa74cd
4,click,2021-08-21,Maldives,Malé,Tesher,Jalebi Baby,Jalebi Baby,QZNWQ2070741,2d896d31-97b6-4869-967b-1c5fb9cd4bb8

In [6]:
df.describe(include='all')

,event,date,country,city,artist,album,track,isrc,linkid
count,226278,226278,226267,226267,226241,226273,226273,219157,226278
unique,3,7,211,11993,2419,3254,3562,709,3839
top,pageview,2021-08-19,Saudi Arabia,Jeddah,Tesher,Jalebi Baby,Jalebi Baby,QZNWQ2070741,2d896d31-97b6-4869-967b-1c5fb9cd4bb8
freq,142015,35361,47334,22791,40841,40841,40841,40841,40841

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226278 entries, 0 to 226277
Data columns (total 9 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   event    226278 non-null  object
 1   date     226278 non-null  object
 2   country  226267 non-null  object
 3   city     226267 non-null  object
 4   artist   226241 non-null  object
 5   album    226273 non-null  object
 6   track    226273 non-null  object
 7   isrc     219157 non-null  object
 8   linkid   226278 non-null  object
dtypes: object(9)
memory usage: 15.5+ MB

In [9]:
df.dtypes

event      object
date       object
country    object
city       object
artist     object
album      object
track      object
isrc       object
linkid     object
dtype: object

In [15]:
df[df.isna().any(axis=1)]

,event,date,country,city,artist,album,track,isrc,linkid
278,click,2021-08-20,United States,Philadelphia,YoungBoy Never Broke Again,Top,Boom,NaN,5f86ad60-5c3a-5996-8c4b-b32ccba46e6f
301,click,2021-08-20,United States,Front Royal,YNW Melly,We All Shine,Mixed Personalities (feat. Kanye West),NaN,457538c1-61e2-5f7b-914c-43e85177ec3a
302,click,2021-08-20,United States,Boca Raton,Little Big Town,Restoration: The Songs of Elton John and Berni...,Rocket Man,NaN,c25059fe-2763-5e66-9cce-84e9766d1c4b
305,click,2021-08-20,United States,Stillwater,Lofi Fruits Music,Steven Universe,Steven Universe,NaN,eb28ae21-888f-5440-bd79-05a631f5dccd
312,click,2021-08-20,United States,San Antonio,Sayyhuncho,None Regular,None Regular,NaN,a396942a-04b5-5cfa-9121-7a082081b489
...,...,...,...,...,...,...,...,...,...
226092,pageview,2021-08-19,United States,Lansing,KA$HDAMI,epiphany,ILY/Sincerely,NaN,83691506-2318-5a15-a7c8-602f055fed59
226166,pageview,2021-08-19,United States,San Antonio,Gucci Mane,Everybody Looking,No Sleep - Intro,NaN,9e186531-3b42-566e-a30b-003d56e9530f
226178,pageview,2021-08-20,United States,Snellville,Sammy Kershaw,Haunted Heart,She Don't Know She's Beautiful,NaN,2a20c79c-7578-5247-878b-a6b71fba3769
226181,pageview,2021-08-20,United States,Whitley City,Kiiara,low kii savage,Gold,NaN,ac33e71b-209d-5503-a276-14ca46372a81
226186,pageview,2021-08-20,United States,Atlanta,Maze,Golden Time Of Day (Remastered),I Need You - Remastered,NaN,b8ba0599-0599-586d-88e0-0bcc03bb69c8